language: java
jdk: openjdk11
sudo: required
before_script:
  - psql -c 'create database underwriter;' -U postgres
services:
- docker
- postgresql
after_success:
- bin/docker_push.sh
- bin/kubernetes_deploy.sh
cache:
  directories:
  - $HOME/.m2

notifications:
  email: false

