version: '3'
services:
  test_db:
    image: 'postgres:11.5'
    ports:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=underwriter
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
