package com.hedvig.underwriter.model

enum class Partner(val partnerName:String, val campaignCode: String? = null) {
    HEDVIG("hedvig"),
    INSPLANET("insplanet","f89051cb43"),
    COMPRICER("compricer","8a2fcb2a11"),
    INSURLEY("insurley","eib7soo9va"),
    KEYSOLUTIONS("keysolutions","l8wyjvFfx5"),
    AVY("avy"),
    SPIFF("spiff"),
    TJENSTETORGET("tjenstetorget"),
    FORSIKRINGSPORTALEN("forsikringsportalen"),
    SAMLINO("samlino"),
    FINDFORSIKRING("findforsikring"),
    FORSIKRINGSGUIDEN("forsikringsguiden"),
    KEY_HOLE("key_hole"),
    COPENHAGEN_SALES("copenhagen_sales"),
    CHARLIE("charlie"),
    FLYTTSMART("flyttsmart"),
    PAMIND("pamind"),
    MECENAT("mecenat"),
    HAPPENS("happens"),
    HEMAVI("hemavi"),
    SAMBLA("sambla"),
    PEACH("peach"),
    MMG("mmg"),
}
