server.port: 5698
management.endpoints.web.exposure.include: '*'
logging.level.com.hedvig: INFO

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    platform: POSTGRESQL
    driverClassName: org.postgresql.Driver
    url: ${POSTGRES_URL}/underwriter
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    initialization-mode: never
  liquibase.change-log: classpath:/db/changelog/changelog-master.yml
  liquibase.enabled: false
  jackson.deserialization.read-unknown-enum-values-using-default-value: true

graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true
    actuator-metrics: true

graphiql:
  mapping: /graphiql
  endpoint:
    graphql: /graphql
  enabled: true
  pageTitle: Underwriter GraphiQL

graphcms:
  project: Underwriter
  url: https://api-euwest.graphcms.com/v1/cjmawd9hw036a01cuzmjhplka/master

---
spring:
  profiles: production, staging

server.port: 80
logging.level.com.hedvig: TRACE

cloud.aws:
  region.static: eu-central-1
  stack.auto: false

lokalise:
  projectId: ${LOKALISE_PROJECT_ID}
  apiToken: ${LOKALISE_API_TOKEN}

hedvig:
  notification-service.url: http://notification-service

---
spring:
  profiles: staging

graphql:
  servlet:
    exception-handlers-enabled: true

---
spring:
  profiles: test, development

  liquibase.enabled: true

hedvig:
  notification-service.url: http://localhost:4087

features:
  block-requoting: true
