server.port: 5698

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/underwriter
    username: postgres
  liquibase.change-log: classpath:/db/changelog/changelog-master.yml
  liquibase.enabled: false
  jackson.deserialization.read-unknown-enum-values-using-default-value: true

graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true
    actuator-metrics: true

graphiql:
  mapping: /graphiql
  endpoint:
    graphql: /graphql
  enabled: true
  pageTitle: Underwriter GraphiQL

graphcms.project: Underwriter
graphcms.url: https://api-euwest.graphcms.com/v1/cjmawd9hw036a01cuzmjhplka/master

---
spring:
  profiles: staging

graphql:
  servlet:
    exception-handlers-enabled: true

---
spring:
  profiles: test, development

lokalise:
  useFakes: true
