#server.port: 5698

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/underwriter
    username: postgres
  liquibase.change-log: classpath:/db/changelog/changelog-master.yml
  liquibase.enabled: false
  jackson.deserialization.read-unknown-enum-values-using-default-value: true

